
array_changelog = {
	{"The updater has stopped working.", "Reinstall the mod if you want", "to get latest releases.","", "More info: https://goo.gl/RVU79g"},
	{"The updater has stopped working.", "Reinstall the mod if you want", "to get latest releases.","", "More info: https://goo.gl/RVU79g"},
	{"The updater has stopped working.", "Reinstall the mod if you want", "to get latest releases.","", "More info: https://goo.gl/RVU79g"},
	{"The updater has stopped working.", "Reinstall the mod if you want", "to get latest releases.","", "More info: https://goo.gl/RVU79g"},
	{"The updater has stopped working.", "Reinstall the mod if you want", "to get latest releases.","", "More info: https://goo.gl/RVU79g"},
	{"The updater has stopped working.", "Reinstall the mod if you want", "to get latest releases.","", "More info: https://goo.gl/RVU79g"},
	{"The updater has stopped working.", "Reinstall the mod if you want", "to get latest releases.","", "More info: https://goo.gl/RVU79g"},
	{"The updater has stopped working.", "Reinstall the mod if you want", "to get latest releases.","", "More info: https://goo.gl/RVU79g"},
	{"The updater has stopped working.", "Reinstall the mod if you want", "to get latest releases.","", "More info: https://goo.gl/RVU79g"},
	{"The updater has stopped working.", "Reinstall the mod if you want", "to get latest releases.","", "More info: https://goo.gl/RVU79g"},
	{"The updater has stopped working.", "Reinstall the mod if you want", "to get latest releases.","", "More info: https://goo.gl/RVU79g"},
	{"The updater has stopped working.", "Reinstall the mod if you want", "to get latest releases.","", "More info: https://goo.gl/RVU79g"},
	{"The updater has stopped working.", "Reinstall the mod if you want", "to get latest releases.","", "More info: https://goo.gl/RVU79g"},
	{"The updater has stopped working.", "Reinstall the mod if you want", "to get latest releases.","", "More info: https://goo.gl/RVU79g"},
	{"The updater has stopped working.", "Reinstall the mod if you want", "to get latest releases.","", "More info: https://goo.gl/RVU79g"},
	{"The updater has stopped working.", "Reinstall the mod if you want", "to get latest releases.","", "More info: https://goo.gl/RVU79g"},
	{"The updater has stopped working.", "Reinstall the mod if you want", "to get latest releases.","", "More info: https://goo.gl/RVU79g"},
	{"The updater has stopped working.", "Reinstall the mod if you want", "to get latest releases.","", "More info: https://goo.gl/RVU79g"},
	{"The updater has stopped working.", "Reinstall the mod if you want", "to get latest releases.","", "More info: https://goo.gl/RVU79g"},
	{"The updater has stopped working.", "Reinstall the mod if you want", "to get latest releases.","", "More info: https://goo.gl/RVU79g"},
	{"The updater has stopped working.", "Reinstall the mod if you want", "to get latest releases.","", "More info: https://goo.gl/RVU79g"},
	{"The updater has stopped working.", "Reinstall the mod if you want", "to get latest releases.","", "More info: https://goo.gl/RVU79g"},
	{"The updater has stopped working.", "Reinstall the mod if you want", "to get latest releases.","", "More info: https://goo.gl/RVU79g"},
	{"The updater has stopped working.", "Reinstall the mod if you want", "to get latest releases.","", "More info: https://goo.gl/RVU79g"},
	{"The updater has stopped working.", "Reinstall the mod if you want", "to get latest releases.","", "More info: https://goo.gl/RVU79g"},
	{"The updater has stopped working.", "Reinstall the mod if you want", "to get latest releases.","", "More info: https://goo.gl/RVU79g"},
	{"The updater has stopped working.", "Reinstall the mod if you want", "to get latest releases.","", "More info: https://goo.gl/RVU79g"},
	{"The updater has stopped working.", "Reinstall the mod if you want", "to get latest releases.","", "More info: https://goo.gl/RVU79g"},
	{"The updater has stopped working.", "Reinstall the mod if you want", "to get latest releases.","", "More info: https://goo.gl/RVU79g"},
	{"The updater has stopped working.", "Reinstall the mod if you want", "to get latest releases.","", "More info: https://goo.gl/RVU79g"},
	{"The updater has stopped working.", "Reinstall the mod if you want", "to get latest releases.","", "More info: https://goo.gl/RVU79g"},
	{"The updater has stopped working.", "Reinstall the mod if you want", "to get latest releases.","", "More info: https://goo.gl/RVU79g"}
}
