
array_changelog = {
	{"+ Added 11.4 support (thanks to Nanquitas).", "+ Updated DS Yoshi Falls to its latest version."},
	{"+ Updated OnionFS to latest version (again)."},
	{"+ Updated OnionFS to latest version."},
	{"+ Fixed menu edits to JPN game."},
	{"+ Fixed lag caused by v0.12.3."},
	{"+ Made the 1.1 update patch", "  compatible with CTGP-7.", "", "+ Added JPN MK7 text edits", "  (English only for now)."},
	{"+ Added speedometer plugin,","  (can be enabled in \"Ingame settings\").", "", "- Dropped NTR 3.2 and 3.3 support."},
	{"+ Added Silver Arrow Kart."},
	{"+ Added Gold Mantis Kart.", "+ Added Arcade Kart.", "+ Added MKDS Monster Tires.", "+ Updated Green/Red eggs.", "+ Added cc modifier plugin.", "+ Updated NTR 3.4 to Preview6.", " + Added 11.3 support.", "- Removed LED tricks plugin."},
	{"+ Improved the custom font."},
	{"+ Updated Bandicoot Team Kart."},
	{"+ Removed 1st place beats.", "", "+ Updated N64 Frappe Snowland."},
	{"+ Added DS Yoshi Falls Custom Music.", "+ Added N64 Moo Moo Farm Custom Music."},
	{"+ Now gets updates from releases page."},
	{"+ Bugfixes."},
	{"+ Updated to OnionFS (bugfixes)."},
	{"+ Fixed \"Failed Creating SSL Context\"."},
	{"+ Fixed some repeating ingame text."},
	{"+ Fixed a crash for N3DS users (notification", "  was being added with ntr loaded.)"}, 
	{"+ Fix O3DS 11.2 support.", "+ Fix bugs related to NTR loading."},
	{"+ Added 11.2 support."},
	{"+ Fix N64 Frappe Snowland crash (again).","","+ Replaced smash loading icon with a", "  Mario Kart style animation."},
	{"+ Manager bugfixes."},
	{"+ Updated 200cc plugin","  (now supports all MK7 regions/versions).","","+ Fixed a bug when 200cc and led tricks","  were enabled at same time."},
	{"+ Updated Miku's Birthday Spec.","","+ Updated 200cc plugin","  (autodetects game region/version).","","+ Reduced manager boot time."},
	{"+ Added 11.1 support."},
	{"+ Fixed GBA Cheese Land bug.", "+ Fixed SNES Ghost Valley 2 bug.", "","+ Implemented Nanquitas' BootNTR","  into the manager."},
	{"+ Fixed Banshee Broadwalk 2 lag.", "", "+ Added LED tricks plugin", "  (enable it from ingame settings).", "", "+ Improved the manager."},
	{"+ Added custom music to Concord Town."},
	{"+ Added Elemental Cave.", "+ Added Banshee Broadwalk 2.","","+ Updated Miku's Birthday Spec."},
	{"+ Fixed manager bugs.", "+ Improved the updater.", "","(New BootNTR version,","use BootNTR updater to update it.)"},
	{"+ Fixed some tracks online."},
	{"+ More bug fixes."},
	{"+ Fixed a bug with N3DS","","+ Updated Miku's Birthday Spec."},
	{"+ Update needed to make 0.8 work properly."},
	{"+ Added GBA Cheese Land.", "+ Added Galvarny Falls.", "+ Added GCN Wario Colosseum.", "", "+ Updated N64 Rainbow Road.", "+ Updated GBA Bowser Castle 3.", "+ Updated Miku's Birthday Spec."},
	{"+ Fixed the downloader."}
}
